Repository faboussard/42-irc, pull requests merged in 2024-11, with the labels that each got.

#27 Parsing : done with \r\n this time + Ctrl + D
  includes/Parser.hpp
  includes/utils.hpp
  src/Parser.cpp
  src/messageManagement.cpp
  src/numericReplies.cpp
  src/utils.cpp
Labels: parsing

#34 fix: leak on runtime errors, explanation on the github
  .gitignore
  src/Server.cpp
  src/main.cpp
Labels: fix

#43 Parsing
  Makefile
  includes/Client.hpp
  src/Client.cpp
  src/Parser.cpp
  src/commands/pass.cpp
  src/messageManagement.cpp
Labels: fix

#46 Privmsg
  Makefile
  assets/fanny_notes.md
  includes/Channel.hpp
  includes/Server.hpp
  includes/numericReplies.hpp
  src/Channel.cpp
  src/Config.cpp
  src/Parser.cpp
  src/Server.cpp
  src/commands/join.cpp
  src/commands/kick.cpp
  src/commands/notice.cpp
  src/commands/pass.cpp
  src/commands/privmsg.cpp
  src/messageManagement.cpp
  src/numericReplies.cpp
Labels: enhancement
